spring.application.name=digitalVotingApp
server.port=1550

spring.datasource.url=jdbc:mysql://localhost:3306/e_voting_app
#spring.datasource.driver-class-name=
spring.datasource.username=root
    spring.datasource.password=glory12345-6
spring.datasource.integratedSecurity=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true